---
name: CI
'on':
  push:
  workflow_dispatch:

jobs:
  test_commons:
    uses: LogPass/reusable-workflows/.github/workflows/test_commons.yml@main

  test_devops:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: lint GitHub Actions workflows
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check
          fail_on_error: true
          actionlint_flags: -pyflakes=
