---
name: '*misspell'
'on':
  workflow_call:
    inputs:
      timeout-minutes:
        description: Misspell `build` job timeout in minutes
        required: false
        type: number
        default: 5
      pr-committer:
        description: Pull Request committer
        required: false
        type: string
        default: logpass-bot <github-bot@logpass.me>
      pr-author:
        description: Pull Request author
        required: false
        type: string
        default: logpass-bot <github-bot@logpass.me>
      pr-branch:
        description: Pull Request branch
        required: false
        type: string
        default: fix/misspell-fixer/typos
      pr-reviewers:
        description: New-line separated usernames of PR reviewers
        type: string
        required: false
      pr-team-reviewers:
        description: New-line separated team names added to PR reviewers
        type: string
        required: false
    secrets:
      token:
        description: GitHub token used to create Pull Request
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: "${{ inputs.timeout-minutes }}"
    steps:
      - uses: actions/checkout@v2
      - uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@v3.12.1
        with:
          token: "${{ secrets.token }}"
          committer: "${{ inputs.pr-committer }}"
          author: "${{ inputs.pr-author }}"
          commit-message: "fix: fix typos by misspell-fixer"
          branch: "${{ inputs.pr-branch }}"
          delete-branch: true
          title: "fix: typos fixes by misspell-fixer"
          reviewers: "${{ inputs.pr-reviewers }}"
          team-reviewers: "${{ inputs.pr-team-reviewers }}"
